### PR TITLE
Option to skip plotting wall in equilibrium_CX

### LINKED ISSUE #97: Sample equilibrium data are transposed
2d profile data in `samples/sample_equilibrium_ods.json` are transposed

image

Things in `ods['equilibrium']['time_slice'][0]['profiles_2d'][0]` that should be transposed back:
- phi
- psi
- b_field_tor

### PR DESCRIPTION
**Pull request by eldond**
- This is useful when trying to cycle through different limiter files
- Might not want to edit the ODS itself to put them in (keep the original in there)
- Needed to support https://github.com/gafusion/OMFIT-source/pull/4411
- Also fix sample data and close #97

### CODE REVIEW

**Comment by eldond** [comment]
@orso82 I don't know what to do about the travis failure. It looks like a netcdf4 installation problem, or something. Not sure.

**Comment by eldond** [comment]
@orso82 Do you have any suggestions for how to fix this?

**Comment by orso82** [comment]
Not sure. Something must have changed on the Travis side. Perhaps we can try to lock the version of NetCDF4 in the setup.py script https://github.com/gafusion/omas/blob/master/setup.py to a previous version.

**Comment by eldond** [comment]
> just having Cython version x.y installed on your system is entirely irrelevant if a certain package that you install was built with an older Cython version that has a bug.


https://github.com/cython/cython/issues/1953#issuecomment-398128940

**Comment by eldond** [comment]
This failed run has
```
Collecting netCDF4 (from omas==0.55.2)
  Downloading https://files.pythonhosted.org/packages/bf/da/79d6762e0ef66f913249684122d567bddfada6b83cdf9e96c82550fd2d14/netCDF4-1.5.3-cp37-cp37m-manylinux1_x86_64.whl (4.1MB)
```
vs. a previous successful run:
```
Collecting netCDF4 (from omas==0.55.1)
  Downloading https://files.pythonhosted.org/packages/bf/da/79d6762e0ef66f913249684122d567bddfada6b83cdf9e96c82550fd2d14/netCDF4-1.5.3-cp37-cp37m-manylinux1_x86_64.whl (4.1MB)
```

It's the same netcdf4 version

**Comment by eldond** [comment]
Changes to package versions between a good travis run (for #94) and now:
- boto3 changed from 1.12.18 to 1.12.27
- matplotlib changed from 3.2.0 to 3.2.1
- xarray from 0.15.0 to 0.15.1
- cftime from 1.1.0 to 1.1.1.2
- botocore from 1.15.18 to 1.15.27
- pandas 1.0.1 to 1.03

**Comment by eldond** [comment]
The error we're facing is
```
AttributeError: type object 'netCDF4._netCDF4._MemBuf' has no attribute '__reduce_cython__'
```

I found https://github.com/pynbody/pynbody/issues/503:

> Update: the issue was that when I updated cython, I did it using conda update. I redid it by pip install --upgrading, then I installed pynbody from GitHub, and finally, pip install --upgrade numpy. Now I can import the package without any problems. I guess the bottom line is that updating with pip works better than with conda.

MAybe that's not it.

In the travis log, I found
```
xarray 0.15.1 has requirement setuptools>=41.2, but you'll have setuptools 40.8.0 which is incompatible.
```

**Comment by eldond** [comment]
First mention of old setup tools is in 
```
Requirement already satisfied: setuptools in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from pint->omas==0.55.2) (40.8.0)
```

**Comment by eldond** [comment]
What does this thing thing it's doing to the setuptools version?
```
Collecting cython>=0.29.5 (from omas==0.55.2)
  Downloading https://files.pythonhosted.org/packages/7c/60/eb015186ab458f2923ae1713f5f2bb167bd6ca85b8138233f918582cdbc6/Cython-0.29.16-cp37-cp37m-manylinux1_x86_64.whl (2.1MB)
Collecting setuptools>=41.2 (from omas==0.55.2)
  Downloading https://files.pythonhosted.org/packages/a0/df/635cdb901ee4a8a42ec68e480c49f85f4c59e8816effbf57d9e6ee8b3588/setuptools-46.1.3-py3-none-any.whl (582kB)

...

Installing collected packages: cython, setuptools, uncertainties, pint, cftime, netCDF4, jmespath, docutils, python-dateutil, urllib3, botocore, s3transfer, boto3, kiwisolver, pyparsing, cycler, matplotlib, scipy, h5py, pymongo, dnspython, xmltodict, pytz, pandas, xarray, omas
  Found existing installation: setuptools 40.8.0
    Uninstalling setuptools-40.8.0:
      Successfully uninstalled setuptools-40.8.0
```

**Comment by eldond** [comment]
THANKS, NUMPY

**Comment by eldond** [comment]
With the partial rollback, I get this error in pip again:
```
xarray 0.15.1 has requirement setuptools>=41.2, but you'll have setuptools 40.8.0 which is incompatible.
```
So maybe I should put setuptools back.

**Comment by eldond** [comment]
@orso82 It's ready

**Comment by orso82** [comment]
@eldond cannot thank you enough 🥇

**Pull request merged**
