### PR TITLE
Update to use IMAS 3.40.0

### PR DESCRIPTION
**Pull request by bechtt**
The primary changes (that I am aware of) in this version of IMAS are: 
1) Renamed gyrokinetic ids to gyrokinetic_local
2) Restructured pulse_schedule ids to eliminate pulse_schedule.*.*.data and pulse_schedule.*.*.time entries 
3) Extended the equilibrium ids to include more coordinate options for relevant ids (R, Z, psi, phi, rho_tor_norm) and added an overall chi_squared_reduced metric

Some EFIT machine mapping fixes are also included in this PR along with a name change in some mhdin.dat file variables.

test_omas_dynamic_machine was turned off in this PR because of issue #284.

This is accompanied by the OMFIT PR https://github.com/gafusion/OMFIT-source/pull/6889 and should not be merged until all tests are passing there

### CODE REVIEW

**Comment by bechtt** [comment]
Any opposition to this merge?  If not can someone do the honor?

**Comment by hassec** [comment]
@smithsp any chance we could update the website to reflect this imas update?

**Comment by bechtt** [comment]
I think it should be updated automatically as part of the merge pipeline, but sometimes this breaks.  The OMFIT website wasn't updating recently either, but it seems to be now, so maybe something similar is happening with the OMAS site?

**Comment by hassec** [comment]
@bechtt I'm not sure it really works automatically for omas, see discussion in https://github.com/gafusion/omas/issues/279

**Comment by bechtt** [comment]
That's a great point.  Do you have any updates on whether OMAS pages are/can be built in the pipeline @kalling?

**Comment by hassec** [comment]
just for reference, this is fixed since yesterday thanks to @orso82 🎉

**Comment by orso82** [comment]
@torrinba sorry I missed your message. As a repo admin you should now be able to build and update the documentation yourself. Just do `make docs` at the top level OMAS folder (`make html` to build it locally without making it live).

**Pull request merged**
