### PR TITLE
Added note to omas_dynamic_machine example for required imports

### PR DESCRIPTION
**Pull request by dboeckenhoff**
Solving #149

### CODE REVIEW

**Comment by dboeckenhoff** [comment]
Ci failed in build stage with unit tests. Locally on my machine tests run fine and pass. Not sure what is the problem. Any idea?

**Comment by orso82** [comment]
@dboeckenhoff I know that your commit was solicited by @smithsp comment, but I have decided to revert your commit and simply added a note at the beginning of the example that states that to run the MDSplus and omfit_classes are required. I'd really like to keep the examples as focused as possible on the OMAS library itself.

**Comment by orso82** [comment]
@dboeckenhoff I don't know why the regression tests are failing now... I am looking into it

**Comment by orso82** [comment]
@dboeckenhoff it has to be something in the environment, since an empty commit to a separate branch that was previously ok, also shows a fail:
image

**Pull request merged**
