### PR TITLE
test branch for Joey to work on k-files generation for NSTX

### PR DESCRIPTION
**Pull request by jmcclena**
@orso82 This is a branch for testing a fix for fixing issue https://github.com/gafusion/OMFIT-source/issues/6061 by adding in dummy values if mds+ can't be connected to. As validity doesn't exist for pf_active signals, what do you think is the best way to implement some pass if certain coils can't be retrieved from mds+.

### CODE REVIEW

**Comment by jmcclena** [comment]
Hmmm... if looks like the signals do not exist below discharge:133139

**Comment by orso82** [comment]
I don't think the issue is with the data fetching code itself. The question is: why are we looking for 18 signals when there are only 15 available? are we using the right signals.dat/mhdin.dat files?

**Comment by smithsp** [comment]
@jmcclena doesn't like this approach.

**Comment by smithsp** [comment]
Superceded by work in #193

**Pull request closed without merging**
