### PR TITLE
Finish setting up the mhdin.dat file for CMOD to work with the machine independent style

### PR DESCRIPTION
**Pull request by bechtt**
This file came from an old fork of EFIT/EFUND and had only been partially updated to work with the newer format.  Jason Parisi brought this to our attention and made most of the changes to get it working.

### CODE REVIEW

**Review by jmcclena — APPROVED** [review]

**Comment by lajz** [comment]
Hi @jmcclena, are there any examples of using this support file to query cmod? Thanks!

**Comment by jmcclena** [comment]
@lajz Right now we only have the mhdin.dat file for cmod. This specifies more static hardware information such as coil locations. To query for cmod data, a machine mapping would need to be created and filled out.

**Comment by lajz** [comment]
Cool @jmcclena , thanks for the quick reply! Do you know if anyone has previously made an attempt to create the mappings?

**Comment by jmcclena** [comment]
@lajz not to my knowledge

**Pull request merged**
