### PR TITLE
Add currents to omas summary

### PR DESCRIPTION
**Pull request by jmcclena**
@TimSlendebroek in doing this, I change some of the behavior some of the other summary routines to avoid modifying original ods with the summary routines. Could you verify that I didn't break anything? I checked that the STEP regression still passes.

### CODE REVIEW

**Comment by TimSlendebroek** [comment]
I tried running this @jmcclena 

```python
OMFIT['ods']= ods= ODS().sample()

ods.physics_core_profiles_consistent()
del ods['summary.global_quantities']
ods.physics_summary_currents()
```

But the global_quantities currents aren't there :(

**Comment by jmcclena** [comment]
This bot is brutal. I made a commit last week.

**Comment by orso82** [comment]
I think the bot only looks for the [no-pr-activity](https://github.com/gafusion/omas/labels/no-pr-activity) label, independently of whether there has been activity or not...

**Comment by jmcclena** [comment]
@TimSlendebroek Anything else we should change with this pull request?

**Comment by TimSlendebroek** [comment]
Let's push it :)

**Pull request merged**
