### PR TITLE
Plot label offsets can be iterable

### PR DESCRIPTION
**Pull request by eldond**
- Give each label its own unique offset by providing a list or array of offsets
- Previously, label_r_shift and label_z_shift had to be scalars.

``` python
ods = OMFIT['efitviewer']['efitviewer_ods']  # Get an ODS with some slices in it somehow
label_r_shift = [
    0,
    0.25,
    [0.5, 0],
    [0.5, -0.25],
]
axs, axsf = square_subplots(len(label_r_shift), sharex=True, sharey=True)
for i in range(len(label_r_shift)):
    ax = axsf[i]
    ods.plot_equilibrium_CX(time_index=50, ax=ax)  # It doesn't matter which slice; just pick one
    ods.plot_gas_injection_overlay(which_gas=['GASA', 'PFX1'], label_r_shift=label_r_shift[i], ax=ax)
    ax.set_title(label_r_shift[i])
```

image

### CODE REVIEW

**Comment by orso82** [comment]
@eldond can you add a figure to this PR that illustrates this new feature.
Also as a minor comment and request, in general, could you please add an empty line between each `:param ...:` in the docstrings.

**Comment by orso82** [comment]
@eldond looks good. Let me know if you are done and want it merged.

**Comment by eldond** [comment]
@orso82 As soon as it passes. Might be slow because I'm on vacation or whatever. Can't resist a spot of coding before the kids wake up, though.

**Comment by eldond** [comment]
@orso82 I'm guessing these coverage changes in files I didn't touch are due to master being updated while I had this open. I recommend either merging master in here if you care about this in detail, or just merging this into master now because I think it's done.

**Pull request merged**
