### PR TITLE
refactor(test) remove workaround for old omfit_classes version

### PR DESCRIPTION
**Pull request by hassec**
@kalling As promised, removing the workaround now that `omfit_classes` is updated

### CODE REVIEW

**Comment by hassec** [comment]
Interesting, it installed `omfit_classes==3.2024.9.2` but failed. Will investigate

**Comment by kalling** [comment]
@hassec It looks like the new master wasn't created yet. I am guessing some (OMFIT) tests failed, but will take a look. (The new package has the previous master, just much newer one than the last package posted to pypi)

**Comment by kalling** [comment]
(I am basically saying the fixed code isn't in the pypi package yet)

**Comment by hassec** [comment]
@kalling Where would I be able to see/check if a new `omfit_classes` is deployed? (to avoid bugging you here 😅)

**Comment by kalling** [comment]
`omfit_classes` got updated on pypi yesterday due to the new master release, so theoretically the fix should be in.

**Comment by hassec** [comment]
@kalling yep just reran the tests and they now all pass 🎉

**Pull request closed without merging**
