### PR TITLE
Test new efit mappings for ida

### PR DESCRIPTION
**Pull request by AreWeDreaming**
This should be merged after ~~#255~~ and ~~#256~~ 
This changes has three parts:
- Changes to `omas_imas` to allow storing  ODS data into IDS directly in memory
- Added `if_bandwidth` to DIII-D ECE
- Add mapping between flux coordinates from #222 
- Switched from obsolete `b_r` to `b_field_r` etc.

### CODE REVIEW

**Comment by AreWeDreaming** [comment]
Needs #256 to be merged first.

**Comment by AreWeDreaming** [comment]
Merged master into branch trying to fix regression

**Comment by AreWeDreaming** [comment]
This should be ready to review and merge. Tests are passing to!

**Review by smithsp — APPROVED** [review]
Looks ok to me.

**Comment by AreWeDreaming** [comment]
@smithsp Should we create a PR with an OMAS update to this branch first or do we merge first?

**Comment by smithsp** [comment]
Every commit to master branch of omas pushes a commit to auto_merge branch of OMFIT to update OMFIT's omas, which would trigger tests on that side.

**Pull request merged**
