### PR TITLE
Add option to remove integrator drift

### PR DESCRIPTION
**Pull request by odstrcilt**
Flux loop signals and magnetics probe signals can have nonnegligible errors caused by the analog integrator drift. Assuming that the drift is linear in time, this will set signals back to zero after the end of the discharge.

### CODE REVIEW

**Comment by orso82** [comment]
@odstrcilt perhaps you forgot to commit the `remove_integrator_drift` function?

**Comment by odstrcilt** [comment]
@orso82 do you have any guess what is causing the regression test to fail? It does not seem to be related to any changes done by me.

**Comment by smithsp** [comment]
@odstrcilt It looks like you ended up with a branch of omas that depends on a new DD from IMAS, where the EC launchers have changed structure.  @orso82 Does this imply that we need to address the launchers on omas now?

**Comment by orso82** [comment]
Yes @smithsp we made changes on a OMFIT branch, but we still need to address this on the OMAS side. Mostly it's about the regression tests and machine mappings.

**Comment by smithsp** [comment]
Need to merge with `master`.

**Comment by smithsp** [comment]
Still need to merge with master branch.

**Comment by smithsp** [comment]
@odstrcilt 
When @orso82 originally looked into fetching NSTX data using omas, he had gone to great lengths to compare what was fetched to the existing k-files.  How do these changes affect that comparison and validation?

**Comment by orso82** [comment]
@odstrcilt in case it's needed, you can look at the https://github.com/gafusion/OMFIT-source/blob/unstable/modules/EFITtime/SCRIPTS/NSTX/update_keqdsk_from_omas.py script, and in particular use the `OMFITkeqdsk.compare_omas_constraints` function.

**Comment by smithsp** [comment]
Ping @odstrcilt to compare to previous k-files.

**Comment by odstrcilt** [comment]
I have tested shot  133964 at 285ms

Here is compared OMAS case with and without drift substraction
image

Here is OMAS with drift subtraction compared to EFIT01 kfile
image

Here is OMAS without drift subtraction compared to EFIT01 kfile
image

I will try to plot also timetraces...

**Comment by odstrcilt** [comment]
@orso82 can we merge it?

**Comment by orso82** [comment]
A

**Pull request merged**
