### PR TITLE
add mse cocos

### PR DESCRIPTION
**Pull request by jmcclena**

### CODE REVIEW

**Comment by orso82** [comment]
@jmcclena have you tested to see if this works?

**Comment by jmcclena** [comment]
hmm... I was hopeful it would as it didn't crash omas. I just tested it though and it does not work :(.

**Comment by jmcclena** [comment]
I tried adding 

```
 944                     elif isinstance(transform,numpy.array):
 945                         norm = np.ones(len(transform))
 946                         for itf,tf in enumerate(transform):
 947                             norm[itf] = omas_physics.cocos_transform(self.cocosio, self.cocos)[tf]
```

to `omas_core.py`, but that didn't seem to fix it

**Comment by jmcclena** [comment]
@orso82 Okay, this pull request works for me 

```
from omas import *
import numpy as np
ods = load_omas_pkl('ods.pkl')

ods['mse.channel.0.active_spatial_resolution.0.geometric_coefficients'] = np.ones(9)
with omas_environment(ods,cocosio=2):
    print(ods['mse.channel.0.active_spatial_resolution.0.geometric_coefficients'])
```
returns 
```
[ 1.  1. -1.  1.  1.  1. -1.  1.  1.]

```

**Comment by orso82** [comment]
Really nice job @jmcclena ! 🥇 
As a refinement, could we consider using a list instead of numpy array to define the transform?

**Comment by orso82** [comment]
Great job @jmcclena !

**Pull request merged**
